from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib import messages
from attendance.models import Lecture, AttendanceRecord, Attendance
from accounts.models import Student
from django.shortcuts import redirect
import io
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment

@login_required
def student_attendance_report(request, lecture_id):
    if not request.user.is_teacher:
        return render(request, 'attendance/access_denied.html', status=403)

    lecture = get_object_or_404(Lecture, pk=lecture_id)
    teacher = lecture.teacher
    students = lecture.lecture_class.students.all().order_by('roll_no')
    attendance_records = AttendanceRecord.objects.filter(lecture=lecture).order_by('date')
    # Update dates to include both date and record ID
    record_data = [{'date': record.date, 'id': record.id} for record in attendance_records]

    student_data = []
    for student in students:
        student_attendance = []
        total_days = len(attendance_records)
        present_days = 0

        for record in attendance_records:
            attendance = Attendance.objects.filter(
                attendance_record=record, student=student
            ).first()
            status = attendance.attendance_status if attendance else 'absent'
            student_attendance.append(status)
            if status == 'present':
                present_days += 1

        percentage = (present_days / total_days * 100) if total_days > 0 else 0
        student_data.append({
            'roll_no': student.roll_no,
            'name': student.first_name + ' ' + student.last_name,
            'attendance': student_attendance,
            'percentage': round(percentage)
        })

    if 'download_pdf' in request.GET:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=landscape(A4),
            topMargin=1*inch,
            bottomMargin=1*inch,
            leftMargin=1*inch,
            rightMargin=1*inch
        )
        elements = []

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'TitleStyle',
            parent=styles['Heading1'],
            fontSize=18,
            leading=22,
            textColor=colors.HexColor('#1E3A8A'),
            spaceAfter=12,
            alignment=1
        )
        subtitle_style = ParagraphStyle(
            'SubtitleStyle',
            parent=styles['Normal'],
            fontSize=12,
            leading=14,
            textColor=colors.HexColor('#4B5563'),
            spaceAfter=10,
            alignment=1
        )
        header_left_style = ParagraphStyle(
            'HeaderLeftStyle',
            parent=styles['Normal'],
            fontSize=10,
            leading=12,
            textColor=colors.HexColor('#4B5563'),
            alignment=0
        )
        header_right_style = ParagraphStyle(
            'HeaderRightStyle',
            parent=styles['Normal'],
            fontSize=10,
            leading=12,
            textColor=colors.HexColor('#4B5563'),
            alignment=2
        )

        elements.append(Paragraph(
            f"Generated by: {teacher.first_name} {teacher.last_name}",
            header_left_style
        ))
        elements.append(Paragraph(
            f"Generated on: {timezone.now().strftime('%d/%m/%Y %H:%M %p PKT')}",
            header_right_style
        ))
        elements.append(Spacer(1, 0.1*inch))
        elements.append(Paragraph(f"Attendance Report", title_style))
        elements.append(Paragraph(
            f"Lecture: {lecture} | Class: {lecture.lecture_class}",
            subtitle_style
        ))

        table_data = [['Roll No', 'Student'] + [record['date'].strftime('%d/%m/%Y') for record in record_data] + ['Percentage']]
        for student in student_data:
            row = [student['roll_no'], student['name']] + student['attendance'] + [f"{student['percentage']}%"]
            table_data.append(row)

        col_widths = [0.8*inch, 2.5*inch] + [0.9*inch]*len(record_data) + [1*inch]
        table = Table(table_data, colWidths=col_widths)
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1E3A8A')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
            ('TOPPADDING', (0, 0), (-1, 0), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#F3F4F6'), colors.white]),
        ]))
        elements.append(table)

        def add_page_number(canvas, doc):
            page_num = canvas.getPageNumber()
            canvas.setFont("Helvetica", 9)
            canvas.setFillColor(colors.grey)
            canvas.drawCentredString(landscape(A4)[0]/2, 0.5*inch, f"Page {page_num}")
            canvas.setFont("Helvetica-Oblique", 8)
            canvas.setFillColor(colors.grey)
            canvas.drawCentredString(landscape(A4)[0]/2, 0.35*inch, "This is a system-generated report.")
            canvas.saveState()
            canvas.setFont("Helvetica-Bold", 60)
            canvas.setFillColor(colors.grey, alpha=0.1)
            canvas.rotate(45)
            canvas.drawCentredString(5*inch, -1*inch, "AttendXMark")
            canvas.restoreState()

        doc.build(elements, onFirstPage=add_page_number, onLaterPages=add_page_number)
        buffer.seek(0)
        response = HttpResponse(buffer, content_type='application/pdf')
        current_date = timezone.now().strftime('%d/%m/%Y')
        file_name = f"{lecture.lecture_class} - {current_date.replace('/', '-')}.pdf"
        response['Content-Disposition'] = f'attachment; filename="{file_name}"'
        return response

    if 'download_excel' in request.GET:
        wb = Workbook()
        ws = wb.active
        ws.title = "Attendance Report"
        headers = ['Roll No', 'Student'] + [record['date'].strftime('%d/%m/%Y') for record in record_data] + ['Percentage']
        ws.append(headers)
        for cell in ws[1]:
            cell.font = Font(bold=True)
            cell.alignment = Alignment(horizontal='center')
        for student in student_data:
            row = [student['roll_no'], student['name']] + student['attendance'] + [f"{student['percentage']}%"]
            ws.append(row)
        for col in ws.columns:
            max_length = 0
            column = col[0].column_letter
            for cell in col:
                try:
                    if len(str(cell.value)) > max_length:
                        max_length = len(str(cell.value))
                except:
                    pass
            adjusted_width = (max_length + 2)
            ws.column_dimensions[column].width = adjusted_width
        buffer = io.BytesIO()
        wb.save(buffer)
        buffer.seek(0)
        response = HttpResponse(
            buffer,
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )
        current_date = timezone.now().strftime('%d/%m/%Y')
        file_name = f"{lecture.lecture_class} - {current_date.replace('/', '-')}.xlsx"
        response['Content-Disposition'] = f'attachment; filename="{file_name}"'
        return response

    context = {
        'lecture': lecture,
        'record_data': record_data,  # Updated to pass record_data instead of dates
        'student_data': student_data,
    }
    return render(request, 'reports/student_attendance_report.html', context)

@login_required
def delete_attendance(request, lecture_id, attendance_record_id):
    if not request.user.is_teacher:
        return render(request, 'attendance/access_denied.html', status=403)

    lecture = get_object_or_404(Lecture, pk=lecture_id)
    if lecture.teacher != request.user:
        return render(request, 'attendance/access_denied.html', status=403)

    record = get_object_or_404(AttendanceRecord, id=attendance_record_id, lecture=lecture)
    record_date = record.date.strftime('%d/%m/%Y')
    record.delete()
    messages.success(request, f"Attendance record for {record_date} deleted successfully.")
    return redirect('student_attendance_report', lecture_id=lecture_id)


@login_required
def teacher_lectures_report(request):
    if not request.user.is_teacher:
        return render(request, 'attendance/access_denied.html', status=403)

    lectures = Lecture.objects.filter(teacher=request.user, lecture_class__isnull=False).order_by("start_time")
    return render(request, 'reports/teacher_lectures_report.html', {'lectures': lectures, 'user': request.user})