# Generated by Django 5.1.4 on 2025-02-27 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, help_text='The room number where the class is held (e.g., B-101)', max_length=50, null=True)),
                ('section', models.CharField(blank=True, help_text='The section of the class (e.g., A, B, C)', max_length=10, null=True)),
                ('name', models.CharField(help_text="The name or code of the class (e.g., 'Mathematics 101')", max_length=255)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='subjects.department')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='subjects.semester')),
                ('students', models.ManyToManyField(blank=True, related_name='classes_enrolled', to='accounts.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_taught', to='accounts.teacher')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'unique_together': {('name', 'section', 'semester')},
            },
        ),
    ]
