# Generated by Django 5.1.4 on 2025-02-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='major',
            new_name='discipline',
        ),
    ]
