# Generated by Django 5.1.4 on 2025-03-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_is_staff'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(blank=True, to='subjects.course'),
        ),
    ]
