# Generated by Django 5.1.4 on 2025-03-18 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_teacher_courses'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.ForeignKey(blank=True, help_text='The section of the class (e.g., A, B, C)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='subjects.section'),
        ),
    ]
