# Generated by Django 5.1.4 on 2025-04-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_class_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='degree_level',
        ),
    ]
