# Generated by Django 5.1.4 on 2025-04-05 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_customuser_degree_level'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.degreelevel'),
        ),
    ]
