# Generated by Django 5.1.4 on 2025-04-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_student_degree_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='discipline',
        ),
    ]
