# Generated by Django 5.1.4 on 2025-04-05 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_customuser_discipline'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.discipline'),
        ),
    ]
