# Generated by Django 5.1.4 on 2025-04-05 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_student_discipline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='semester',
        ),
    ]
