# Generated by Django 5.1.4 on 2025-04-08 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_customuser_is_active'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.section'),
        ),
        migrations.AddField(
            model_name='student',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.shift'),
        ),
    ]
