# Generated by Django 5.1.4 on 2025-04-08 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_student_section_student_shift'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='degree_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.degreelevel'),
        ),
        migrations.AddField(
            model_name='class',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.discipline'),
        ),
        migrations.AddField(
            model_name='class',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.shift'),
        ),
    ]
