# Generated by Django 5.1.4 on 2025-04-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_class_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
