# Generated by Django 5.1.4 on 2025-08-15 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_personalinfootp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
    ]
