# Generated by Django 5.1.4 on 2025-04-08 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, help_text='The room number where the class is held (e.g., B-101)', max_length=50, null=True)),
                ('name', models.CharField(help_text="The name or code of the class (e.g., 'Mathematics 101')", max_length=255)),
                ('degree_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.degreelevel')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='subjects.department')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.discipline')),
                ('section', models.ForeignKey(blank=True, help_text='The section of the class (e.g., A, B, C)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='subjects.section')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='subjects.semester')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.shift')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'unique_together': {('name', 'section', 'semester')},
            },
        ),
    ]
