# Generated by Django 5.1.4 on 2025-05-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='session',
            field=models.CharField(blank=True, help_text='The session of the class (e.g., 21 - 25)', max_length=7, null=True),
        ),
    ]
