# Generated by Django 5.1.4 on 2025-01-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='description',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='title',
            new_name='subject',
        ),
    ]
