# Generated by Django 5.1.4 on 2025-03-01 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_capturedface'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='teacher',
            field=models.ForeignKey(default=None, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_leaves', to=settings.AUTH_USER_MODEL),
        ),
    ]
