# Generated by Django 5.1.4 on 2025-03-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_attendance_course_attendance_room_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='attendance',
            field=models.ManyToManyField(blank=True, related_name='lectures', to='attendance.attendance'),
        ),
    ]
