# Generated by Django 5.1.4 on 2025-03-11 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_lecture_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='title',
        ),
    ]
