# Generated by Django 5.1.4 on 2025-03-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_remove_lecture_date_remove_lecture_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='days',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], help_text="Enter days as comma-separated values (e.g., 'Mon,Tue,Wed')", max_length=50),
        ),
    ]
