# Generated by Django 5.1.4 on 2025-03-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_lecture_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='days',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text="Enter days as comma-separated values (e.g., 'Mon,Tue,Wed')", max_length=50),
        ),
    ]
