# Generated by Django 5.1.4 on 2025-03-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_lecture_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='days',
        ),
        migrations.AddField(
            model_name='lecture',
            name='days',
            field=models.ManyToManyField(related_name='lectures', to='attendance.day'),
        ),
    ]
