# Generated by Django 5.1.4 on 2025-03-21 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_day_remove_lecture_days_lecture_days'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='semester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='subjects.semester'),
        ),
    ]
