# Generated by Django 5.1.4 on 2025-04-04 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_class_section'),
        ('attendance', '0013_alter_lecture_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='classroom',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to='accounts.class'),
        ),
    ]
