# Generated by Django 5.1.4 on 2025-04-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_lecture_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='classroom',
        ),
    ]
