# Generated by Django 5.1.4 on 2025-04-08 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_remove_lecture_classroom'),
        ('subjects', '0002_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='semester',
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecture_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='subjects.class'),
        ),
    ]
