# Generated by Django 5.1.4 on 2025-04-08 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_remove_lecture_semester_lecture_lecture_class'),
        ('subjects', '0002_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='lecture_class',
        ),
        migrations.AddField(
            model_name='lecture',
            name='semester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='subjects.semester'),
        ),
    ]
