# Generated by Django 5.1.4 on 2025-04-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_alter_lecture_lecture_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
    ]
