# Generated by Django 5.1.4 on 2025-04-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_attendance_is_marked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='is_marked',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], default=None, max_length=20),
        ),
    ]
