# Generated by Django 5.1.4 on 2025-04-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_remove_attendance_is_marked_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_makeup',
            field=models.BooleanField(default=False),
        ),
    ]
