# Generated by Django 5.1.4 on 2025-04-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_attendance_is_makeup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='attendance',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
