# Generated by Django 5.1.4 on 2025-04-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_alter_attendance_options_attendance_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
