# Generated by Django 5.1.4 on 2025-04-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_attendancerecord_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_makeup_class',
            field=models.BooleanField(default=False),
        ),
    ]
