# Generated by Django 5.1.4 on 2025-04-17 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_attendancerecord_is_makeup_class'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
    ]
