# Generated by Django 5.1.4 on 2025-05-01 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_alter_attendancerecord_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CapturedFace',
        ),
    ]
