# Generated by Django 5.1.4 on 2025-05-30 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0033_alter_lecture_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='teacher',
        ),
        migrations.AddField(
            model_name='leave',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='attendance.lecture'),
        ),
    ]
